### ISSUE TITLE
Need 'daterange' syntax for Zincsearch UI documented

### ISSUE THREAD

**Issue by parity-error** [zincsearch/zincsearch#659]
**Is your feature request related to a problem? Please describe.**
When in Zincsearch I need to select 'date' type records by daterange.    I searched through the docs and 
have not found a way to do this.   I don't even know if this is supported at all or just not documented. 

**Describe the solution you'd like**
I would like there to be an additional item in the ZincSearch syntax guide showing a daterange example. 

**Describe alternatives you've considered**
I have found no way to do this from the ZincSearch UI. 

**Additional context**
None. 

Thank you!  Awesome project.

**Comment by hengfeiyang** [comment]
A good question, for now we haven’t provided this feature, you can do it like this:

- stop writing data or just stop zinc server
- Backup data directory 
- Resume writing 

Why you need stop writing data?
- because if you continue write data, the data always change the data in your copy maybe not correct, especially the data index maybe error.

**Comment by hengfeiyang** [comment]
you can use `range` query for it:

https://docs.zincsearch.com/api-es-compatible/search/types/#range
