### ISSUE TITLE
Keep an index of s3

### ISSUE THREAD

**Issue by tchaton** [zincsearch/zincsearch#883]
Hey there,

I have hundreds of buckets and I would like to keep an index of all the files stored within those buckets.

I also control file removal & addition, so I would need to be able to efficiently update and delete rows.

I wonder if zinc would be a good solution for this ?

Best,
T.C

**Comment by hengfeiyang** [comment]
It looks you need some other tools to management your files in s3, maybe write a python script to read or delete files from s3 and convert to ZincSearch API to index or search data.

**Comment by prabhatsharma** [comment]
Take a look at dynamodb. DynamodB is commonly used for this purpose and is a very good solution for this.

**Comment by gedw99** [comment]
Also you can store the meta of you s3 fikes in SQLite 

that’s how arrow s3 keeps a list all everything in s3. It’s cool cause you can ask sql what’s in all your buckets.

Zinc would have to be given a plugin that fires a s3 event via nats that then updates the SQLite db. That not a hard think to do. Minio supports nats events and so do most s3 clouds I think ?

https://min.io/docs/minio/linux/administration/monitoring/publish-events-to-nats.html


It would also work off the FS but you need a fs watcher that also fires the change event via nats . Not hard to do.

@tchaton why though ? I ask because I was thinking of doing this. But I elected to use arrow with iceberg instead and am integrating zinc with arrow
